artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion/kidney-CT-Scan
  source_URL: https://drive.google.com/file/d/1kjwiIrwCcNnpmyv2QMpdOUu57agbPdn_/view?usp=sharing
  local_data_file: artifacts/data_ingestion/kidney-CT-Scan/data.zip
  unzip_dir: artifacts/data_ingestion/kidney-CT-Scan


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5  #here download the model(VGG-16) and save as a "base_model.h5"
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5    #here I am doing updation of the base model by adding custom layer and remove dense layer of VGG-16 and save as a "base_model_updated.h5"


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5               #this model I will use for prediction